"""
Audio manager. Loads the WAV files from assets/audio (generated by
tools/make_audio.py) and exposes simple play/stop helpers. Everything degrades
gracefully: if the mixer cannot be initialised (no sound card, headless run),
every call becomes a no-op.
"""
import os
import time
import pygame

AUDIO_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'assets', 'audio')

SFX_NAMES = ['click', 'place', 'remove', 'rotate', 'bounce', 'boing', 'boom', 'start', 'stop', 'win', 'lose']
LOOP_NAMES = ['wind', 'belt']


class Audio:
    def __init__(self):
        self.enabled = False
        self.muted = False
        self.sounds = {}
        self.loops = {}
        self.loop_channels = {}
        self.current_music = None
        self._last_played = {}
        try:
            if pygame.mixer.get_init() is None:
                pygame.mixer.init(22050, -16, 1, 512)
            pygame.mixer.set_num_channels(16)
            self.enabled = True
        except pygame.error:
            return
        if not os.path.isdir(AUDIO_DIR) or not os.listdir(AUDIO_DIR):
            try:
                from tools.make_audio import main as build_audio
                build_audio()
            except Exception:
                pass
        for name in SFX_NAMES:
            self.sounds[name] = self._load(name)
        for name in LOOP_NAMES:
            self.loops[name] = self._load(name)

    def _load(self, name):
        path = os.path.join(AUDIO_DIR, f"{name}.wav")
        try:
            return pygame.mixer.Sound(path)
        except (pygame.error, FileNotFoundError):
            return None

    # ------------------------------------------------------------ sfx
    def play(self, name, volume=1.0, min_interval=0.0):
        """Plays a one-shot effect. min_interval rate-limits repeated triggers."""
        if not self.enabled or self.muted:
            return
        snd = self.sounds.get(name)
        if snd is None:
            return
        now = time.monotonic()
        if now - self._last_played.get(name, 0.0) < min_interval:
            return
        self._last_played[name] = now
        snd.set_volume(max(0.0, min(1.0, volume)))
        snd.play()

    # ------------------------------------------------------------ loops
    def loop(self, name, volume=1.0):
        if not self.enabled or self.muted:
            return
        snd = self.loops.get(name)
        if snd is None:
            return
        ch = self.loop_channels.get(name)
        if ch is None or not ch.get_busy():
            snd.set_volume(volume)
            self.loop_channels[name] = snd.play(loops=-1)
        else:
            snd.set_volume(volume)

    def stop_loop(self, name):
        ch = self.loop_channels.pop(name, None)
        if ch is not None:
            ch.stop()

    def stop_all_loops(self):
        for name in list(self.loop_channels):
            self.stop_loop(name)

    # ------------------------------------------------------------ music
    def music(self, name, volume=0.6):
        """Switches the background track (no-op if it is already playing)."""
        if not self.enabled or name == self.current_music:
            return
        path = os.path.join(AUDIO_DIR, f"music_{name}.wav")
        try:
            pygame.mixer.music.load(path)
            pygame.mixer.music.set_volume(0.0 if self.muted else volume)
            pygame.mixer.music.play(loops=-1)
            self.current_music = name
            self._music_volume = volume
        except pygame.error:
            pass

    def stop_music(self):
        if self.enabled:
            pygame.mixer.music.stop()
            self.current_music = None

    def toggle_mute(self):
        self.muted = not self.muted
        if not self.enabled:
            return self.muted
        pygame.mixer.music.set_volume(0.0 if self.muted else getattr(self, '_music_volume', 0.6))
        if self.muted:
            self.stop_all_loops()
        return self.muted
